/*
 * AppRepo - Get apps
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type App struct {
	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	LastUpdated string `json:"last-updated,omitempty"`
}

// AssertAppRequired checks if the required fields are not zero-ed
func AssertAppRequired(obj App) error {
	return nil
}

// AssertRecurseAppRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of App (e.g. [][]App), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAppRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aApp, ok := obj.(App)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAppRequired(aApp)
	})
}
