/*
 * AppRepo - Get apps
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AppUpdatePatchRequest struct {
	Id int32 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`
}

// AssertAppUpdatePatchRequestRequired checks if the required fields are not zero-ed
func AssertAppUpdatePatchRequestRequired(obj AppUpdatePatchRequest) error {
	return nil
}

// AssertRecurseAppUpdatePatchRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AppUpdatePatchRequest (e.g. [][]AppUpdatePatchRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAppUpdatePatchRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAppUpdatePatchRequest, ok := obj.(AppUpdatePatchRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAppUpdatePatchRequestRequired(aAppUpdatePatchRequest)
	})
}
